### ISSUE TITLE
is broken

### ISSUE THREAD

**Issue by simon2022** [crawler64/Amazon-Creditcard-Balance-Checker#1]
Unfortunately the script doesn't work anymore after a modification of the page.

**Comment by crawler64** [comment]
jip, still waiting for lbb to get their new system up and running. I still cant login tough. After that i'll take a look if it's still possible to scrape the new page.

**Comment by simon2022** [comment]
Thank you for your efforts.

**Comment by crawler64** [comment]
LBB introduced a 2-Factor-Authentication in this new release. Unfortunately it seems that LBB "forgets" the authentication after another register process. Guess it has something to do with cookies. Still need some time to figure this out

**Comment by simon2022** [comment]
I played a little bit around with it, it looks like you need to set a cookie named "deviceId-{username}" with an unique id which is always the same when try to log in.
So you can read this cookie on your personal browser (which you already trusted) and set the same value in the script.

**Comment by crawler64** [comment]
Great thanks.
Right now i've decided to use the userfolder feature of selenium. Just in case, LBB decides to add more relevant data to check, this could possibly make this script not broken. Hopefully :)
